const loveTarotCards = [
  { name: "The Fool", sentence: "A new romantic journey begins — embrace it with faith and excitement." },
  { name: "The Magician", sentence: "You have the charm and tools to manifest deep love." },
  { name: "The High Priestess", sentence: "Hidden feelings may be at play — trust your intuition." },
  { name: "The Empress", sentence: "Nurturing energy surrounds your love life now." },
  { name: "The Emperor", sentence: "Stability and loyalty are key in your relationship." },
  { name: "The Hierophant", sentence: "Commitment and traditional values guide your love path." },
  { name: "The Lovers", sentence: "A powerful connection or choice in love is present." },
  { name: "The Chariot", sentence: "Take control and move forward confidently in love." },
  { name: "Strength", sentence: "Gentle courage will strengthen your romantic bonds." },
  { name: "The Hermit", sentence: "Time alone can help you understand what you truly want." },
  { name: "Wheel of Fortune", sentence: "Love takes a turn — destiny is shifting in your favor." },
  { name: "Justice", sentence: "Fairness and honesty are vital in your love life now." },
  { name: "The Hanged Man", sentence: "A pause is needed — see love from a new perspective." },
  { name: "Death", sentence: "An ending clears space for a new and meaningful connection." },
  { name: "Temperance", sentence: "Balance and harmony will bring love into alignment." },
  { name: "The Devil", sentence: "Beware of obsession or unhealthy attachment in love." },
  { name: "The Tower", sentence: "A sudden change shakes things — but truth brings growth." },
  { name: "The Star", sentence: "Hope and healing light up your heart's desires." },
  { name: "The Moon", sentence: "Emotions run deep — not all is clear yet in love." },
  { name: "The Sun", sentence: "Joy and openness bring beautiful love energy." },
  { name: "Judgement", sentence: "Past love may return — or healing from it begins." },
  { name: "The World", sentence: "A love cycle completes — you're ready for fulfillment." },
  // Minor Arcana - Wands
  { name: "Ace of Wands", sentence: "A passionate new spark ignites in your love life." },
  { name: "Two of Wands", sentence: "Love is expanding — but decisions lie ahead." },
  { name: "Three of Wands", sentence: "Love is on the horizon — stay hopeful and open." },
  { name: "Four of Wands", sentence: "A joyful relationship or celebration is near." },
  { name: "Five of Wands", sentence: "Misunderstandings or tension may need resolving." },
  { name: "Six of Wands", sentence: "You’re being recognized and admired in love." },
  { name: "Seven of Wands", sentence: "Defend your heart — stand firm in love choices." },
  { name: "Eight of Wands", sentence: "Romance speeds up — expect fast developments." },
  { name: "Nine of Wands", sentence: "You’ve been hurt — but you’re stronger now." },
  { name: "Ten of Wands", sentence: "Love feels heavy — release burdens to reconnect." },
  { name: "Page of Wands", sentence: "Flirtation or exciting new energy is arriving." },
  { name: "Knight of Wands", sentence: "Passionate encounters spark quickly — enjoy wisely." },
  { name: "Queen of Wands", sentence: "You radiate confidence and attract deep admiration." },
  { name: "King of Wands", sentence: "A bold, charismatic partner could take interest." },
  // Cups
  { name: "Ace of Cups", sentence: "New emotional beginnings overflow with love." },
  { name: "Two of Cups", sentence: "A soulmate bond or deep romantic union blooms." },
  { name: "Three of Cups", sentence: "Joyful gatherings and reconnections bring love." },
  { name: "Four of Cups", sentence: "Emotional dissatisfaction — don’t miss what’s offered." },
  { name: "Five of Cups", sentence: "Loss or regret in love — healing begins with hope." },
  { name: "Six of Cups", sentence: "Nostalgia or a sweet past love may return." },
  { name: "Seven of Cups", sentence: "Too many options — clarity is needed in love." },
  { name: "Eight of Cups", sentence: "You're walking away to find deeper emotional truth." },
  { name: "Nine of Cups", sentence: "Emotional fulfillment is within reach — love yourself first." },
  { name: "Ten of Cups", sentence: "A dreamlike love or happy ending is possible." },
  { name: "Page of Cups", sentence: "A message of love or sweet surprise is coming." },
  { name: "Knight of Cups", sentence: "Romance flows in — a loving gesture is near." },
  { name: "Queen of Cups", sentence: "Emotional depth and compassion bless your love life." },
  { name: "King of Cups", sentence: "A mature, emotionally steady love surrounds you." },
  // Swords
  { name: "Ace of Swords", sentence: "Truth and clarity emerge in matters of the heart." },
  { name: "Two of Swords", sentence: "Love choices feel stuck — follow your inner knowing." },
  { name: "Three of Swords", sentence: "Heartache or past pain may be resurfacing." },
  { name: "Four of Swords", sentence: "Rest and reflection will restore your emotional energy." },
  { name: "Five of Swords", sentence: "Conflict may damage trust — tread carefully in words." },
  { name: "Six of Swords", sentence: "You’re moving on from past emotional turbulence." },
  { name: "Seven of Swords", sentence: "Dishonesty or avoidance may be present in love." },
  { name: "Eight of Swords", sentence: "You feel stuck — but love can’t grow in fear." },
  { name: "Nine of Swords", sentence: "Worry or guilt may be distorting love’s truth." },
  { name: "Ten of Swords", sentence: "A painful ending clears space for true love." },
  { name: "Page of Swords", sentence: "Curiosity or spying may stir love’s waters." },
  { name: "Knight of Swords", sentence: "Someone may rush in — but are they ready for love?" },
  { name: "Queen of Swords", sentence: "Love must meet your standards — stay wise and clear." },
  { name: "King of Swords", sentence: "A logical, thoughtful partner could appear soon." },
  // Pentacles
  { name: "Ace of Pentacles", sentence: "A grounded love or new commitment may begin." },
  { name: "Two of Pentacles", sentence: "Balancing love and life requires care and flow." },
  { name: "Three of Pentacles", sentence: "Working together builds a strong love foundation." },
  { name: "Four of Pentacles", sentence: "Holding on too tightly can block love’s flow." },
  { name: "Five of Pentacles", sentence: "Love feels distant — reach out or seek support." },
  { name: "Six of Pentacles", sentence: "Reciprocity is key — give and receive equally." },
  { name: "Seven of Pentacles", sentence: "Patience will reward your efforts in love." },
  { name: "Eight of Pentacles", sentence: "A relationship deepens through shared effort and care." },
  { name: "Nine of Pentacles", sentence: "Self-love and independence attract true connection." },
  { name: "Ten of Pentacles", sentence: "Long-term love and stability are within reach." },
  { name: "Page of Pentacles", sentence: "A new opportunity for grounded love is arriving." },
  { name: "Knight of Pentacles", sentence: "Steady, reliable love is coming — slow but sure." },
  { name: "Queen of Pentacles", sentence: "A nurturing, stable partner surrounds your path." },
  { name: "King of Pentacles", sentence: "A deeply loyal and generous lover may appear." }
];

module.exports = loveTarotCards;
